# Generated by Django 4.2 on 2023-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0002_barang_atk_jadwal_kategoriatk_kategoriunit_satuanatk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='keterangan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
