# Generated by Django 4.2 on 2023-05-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0003_jadwal_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang_atk',
            name='jumlah_per_satuan',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='keterangan',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(choices=[('D', 'Dirancang'), ('K', 'Konfirmasi Unit'), ('S', 'Diajukan'), ('P', 'Perbaikan')], default='D', max_length=20)),
                ('hasil', models.CharField(choices=[('Y', 'Diterima'), ('N', 'Ditolak')], max_length=20, null=True)),
                ('perbaikan', models.IntegerField(default=0)),
                ('is_terlambat', models.BooleanField(default=False, verbose_name='is terlambat')),
                ('is_aktif', models.BooleanField(default=True, verbose_name='is aktif')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atk.jadwal')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atk.unit')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Isi_pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.BigIntegerField()),
                ('rekomendasi', models.BigIntegerField()),
                ('keterangan', models.TextField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('atk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atk.barang_atk')),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atk.pengajuan')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
