# Generated by Django 4.2 on 2023-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0004_barang_atk_jumlah_per_satuan_alter_jadwal_keterangan_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='isi_pengajuan',
            constraint=models.UniqueConstraint(fields=('atk', 'pengajuan'), name='unique_atk_pengajuan'),
        ),
        migrations.AddConstraint(
            model_name='pengajuan',
            constraint=models.UniqueConstraint(fields=('unit', 'jadwal'), name='unique_unit_jadwal'),
        ),
    ]
