# Generated by Django 4.2 on 2023-05-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0005_isi_pengajuan_unique_atk_pengajuan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='periode_mulai',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='periode_selesai',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='tahun',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2023, max_length=4, verbose_name='year'),
        ),
        migrations.CreateModel(
            name='pengumpulanPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Selesai diajukan'), ('B', 'Tidak/belum diajukan')], default='B', max_length=10)),
                ('tanggalPengumpulan', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atk.jadwal')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atk.unit')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
