# Generated by Django 4.2 on 2023-05-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0006_remove_jadwal_periode_mulai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tahun',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2023, verbose_name='year'),
        ),
    ]
