# Generated by Django 4.2 on 2023-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0007_alter_jadwal_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tahun',
            field=models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2023, verbose_name='year'),
        ),
    ]
