# Generated by Django 4.2 on 2023-05-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0008_alter_jadwal_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='status',
            field=models.CharField(choices=[('B', 'Dibuka'), ('T', 'Ditutup')], default='B', max_length=10),
        ),
    ]
