# Generated by Django 4.2 on 2023-05-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0010_alter_isi_pengajuan_rekomendasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='no_surat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
