# Generated by Django 4.2 on 2023-05-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0011_alter_pengajuan_no_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='isi_pengajuan',
            name='perbaikan',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='hasil',
            field=models.CharField(blank=True, choices=[('Y', 'Diterima'), ('N', 'Ditolak')], max_length=20, null=True),
        ),
    ]
