# Generated by Django 4.2 on 2023-05-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0012_isi_pengajuan_perbaikan_alter_pengajuan_hasil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='progress',
            field=models.CharField(choices=[('D', 'Dirancang'), ('K', 'Konfirmasi Unit'), ('A', 'Diajukan'), ('P', 'Perbaikan'), ('S', 'Selesai')], default='D', max_length=20),
        ),
    ]
