# Generated by Django 4.2 on 2023-05-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0014_stokatk_penggunaanstok_abc_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penggunaanstok',
            name='kegunaan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='penggunaanstok',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='penggunaanstok',
            name='penerima',
            field=models.CharField(choices=[('M', 'Mahasiswa'), ('D', 'Dosen'), ('S', 'Staff'), ('L', 'Lainnya')], default='L', max_length=20),
        ),
    ]
