# Generated by Django 4.2 on 2023-05-22 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0015_penggunaanstok_kegunaan_penggunaanstok_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggunaanstok',
            name='atk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atk.stokatk'),
        ),
    ]
