# Generated by Django 4.2 on 2023-05-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0017_pengambahanstok'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PengambahanStok',
            new_name='PenambahanStok',
        ),
    ]
