# Generated by Django 4.2 on 2023-05-23 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0019_penambahanstok_unit_alter_isi_pengajuan_jumlah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pengajuan_abc_cek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 23, 6, 4, 54, 526441, tzinfo=datetime.timezone.utc)),
        ),
    ]
