# Generated by Django 4.2 on 2023-05-23 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0020_pengajuan_abc_cek_alter_penggunaanstok_tanggal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pengajuan_abc_cek',
            new_name='pengajuanABCCek',
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 23, 7, 6, 42, 475870, tzinfo=datetime.timezone.utc)),
        ),
    ]
