# Generated by Django 4.2 on 2023-05-27 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0023_abc_analysis_model_alter_harga_harga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc_analysis_model',
            name='jumlah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 27, 7, 20, 11, 942345, tzinfo=datetime.timezone.utc)),
        ),
    ]
