# Generated by Django 4.2 on 2023-05-27 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0024_abc_analysis_model_jumlah_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc_analysis_model',
            name='presentase_dana',
        ),
        migrations.RemoveField(
            model_name='abc_analysis_model',
            name='presentase_item',
        ),
        migrations.RemoveField(
            model_name='abc_analysis_model',
            name='presentase_kumulatif_dana',
        ),
        migrations.RemoveField(
            model_name='abc_analysis_model',
            name='presentase_kumulatif_item',
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 27, 10, 32, 26, 877052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='total_pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('rekomendasi', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('atk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atk.barang_atk')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atk.jadwal')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='total_pengajuan',
            constraint=models.UniqueConstraint(fields=('atk', 'jadwal'), name='unique_atk_jadwal'),
        ),
    ]
