# Generated by Django 4.2 on 2023-05-27 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0025_remove_abc_analysis_model_presentase_dana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isi_pengajuan',
            name='perbaikan',
        ),
        migrations.RemoveField(
            model_name='pengajuan',
            name='hasil',
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='tahun',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2023, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='progress',
            field=models.CharField(choices=[('D', 'Dirancang'), ('K', 'Konfirmasi Unit'), ('A', 'Diajukan'), ('P', 'Perbaikan')], default='D', max_length=20),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 27, 14, 10, 43, 628098, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PerbaikanPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(max_length=1000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atk.pengajuan')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
