# Generated by Django 4.2 on 2023-05-27 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0026_remove_isi_pengajuan_perbaikan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='tanggal_konfirmasi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 27, 15, 15, 12, 696927, tzinfo=datetime.timezone.utc)),
        ),
    ]
