# Generated by Django 4.2 on 2023-05-28 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0028_total_pengajuan_harga_total_pengajuan_total_dana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokatk',
            name='jml_keluar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stokatk',
            name='jml_masuk',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 28, 14, 29, 34, 856084, tzinfo=datetime.timezone.utc)),
        ),
    ]
