# Generated by Django 4.2 on 2023-06-01 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0029_stokatk_jml_keluar_stokatk_jml_masuk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc_analysis_model_more',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='penambahanstok',
            options={'ordering': ['-tanggal', '-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='penggunaanstok',
            options={'ordering': ['-tanggal', '-updated', '-created']},
        ),
        migrations.AddField(
            model_name='abc_analysis_model',
            name='persentase_dana',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abc_analysis_model',
            name='persentase_item',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abc_analysis_model',
            name='persentase_kumulatif_dana',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abc_analysis_model',
            name='persentase_kumulatif_item',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 1, 10, 20, 25, 580888, tzinfo=datetime.timezone.utc)),
        ),
    ]
