# Generated by Django 4.2 on 2023-06-01 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0030_abc_analysis_model_more_alter_penambahanstok_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 1, 14, 48, 7, 422131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='abc_analysis_model_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(unique=True)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('dana', models.IntegerField(blank=True, null=True)),
                ('persentase_item', models.FloatField(blank=True, null=True)),
                ('persentase_kumulatif_item', models.FloatField(blank=True, null=True)),
                ('persentase_dana', models.FloatField(blank=True, null=True)),
                ('persentase_kumulatif_dana', models.FloatField(blank=True, null=True)),
                ('prioritas', models.CharField(blank=True, choices=[('A', 'Tinggi'), ('B', 'Sedang'), ('C', 'Rendah')], max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('atk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atk.barang_atk')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
