# Generated by Django 4.2 on 2023-06-01 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0031_alter_penggunaanstok_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_analysis_model_general',
            name='tahun',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 1, 14, 49, 46, 734571, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='abc_analysis_model_general',
            constraint=models.UniqueConstraint(fields=('atk', 'tahun'), name='unique_atk_tahun_abc'),
        ),
    ]
