# Generated by Django 4.2 on 2023-06-05 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0034_guna_alter_penggunaanstok_tanggal_delete_kegunaan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penggunaanstok',
            name='kegunaan',
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 5, 9, 11, 19, 752782, tzinfo=datetime.timezone.utc)),
        ),
    ]
