# Generated by Django 4.2 on 2023-06-08 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0035_remove_penggunaanstok_kegunaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang_atk',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guna',
            name='kegunaan',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 8, 2, 48, 24, 877065, tzinfo=datetime.timezone.utc)),
        ),
    ]
