# Generated by Django 4.2 on 2023-07-11 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0038_pengajuanabccek_dana_pengajuanabccek_persentase_dana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 11, 15, 5, 24, 292000, tzinfo=datetime.timezone.utc)),
        ),
    ]
