# Generated by Django 4.2 on 2023-07-11 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0039_alter_penggunaanstok_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 11, 15, 42, 15, 646799, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='penerimaan_pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atk.pengajuan')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='isi_penerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.TextField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('atk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atk.barang_atk')),
                ('penerimaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atk.penerimaan_pengajuan')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='isi_penerimaan',
            constraint=models.UniqueConstraint(fields=('atk', 'penerimaan'), name='unique_atk_penerimaan'),
        ),
    ]
