# Generated by Django 4.2.3 on 2023-07-13 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0040_alter_penggunaanstok_tanggal_penerimaan_pengajuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 13, 10, 30, 16, 920252, tzinfo=datetime.timezone.utc)),
        ),
    ]
