# Generated by Django 4.2.3 on 2023-07-14 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0042_alter_penerimaan_pengajuan_pengajuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanabccek',
            name='atk',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 14, 16, 20, 51, 822508, tzinfo=datetime.timezone.utc)),
        ),
    ]
