# Generated by Django 4.2.3 on 2023-07-18 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0043_alter_pengajuanabccek_atk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bagumum',
            field=models.BooleanField(default=False, verbose_name='is bagumum'),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 18, 6, 19, 15, 340567, tzinfo=datetime.timezone.utc)),
        ),
    ]
