# Generated by Django 4.2.3 on 2023-07-19 03:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0044_user_is_bagumum_alter_penggunaanstok_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='penyesuaianPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('rekomendasi', models.FloatField(blank=True, null=True)),
                ('prioritas', models.CharField(blank=True, max_length=200, null=True)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('total_dana', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='barang_atk',
            name='harga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barang_atk',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='barang_atk',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barang_atk',
            name='spesifikasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total_pengajuan',
            name='prioritas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 19, 3, 8, 22, 909765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='total_pengajuan',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total_pengajuan',
            name='rekomendasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Harga',
        ),
        migrations.AddField(
            model_name='penyesuaianpengajuan',
            name='total_pengajuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atk.total_pengajuan', unique=True),
        ),
    ]
