# Generated by Django 4.2.3 on 2023-07-19 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0045_penyesuaianpengajuan_barang_atk_harga_barang_atk_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 19, 3, 17, 54, 486749, tzinfo=datetime.timezone.utc)),
        ),
    ]
