# Generated by Django 4.2 on 2025-05-04 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0047_remove_penyesuaianpengajuan_prioritas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='tahun',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2025, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='penggunaanstok',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 5, 4, 3, 43, 40, 748618, tzinfo=datetime.timezone.utc)),
        ),
    ]
